### ISSUE TITLE
Corona Virus Disruption Response Proposal: "NonCon Live!" - Livestream Viewer Application

### ISSUE THREAD

**Issue by criticaltv** [videoDAC/community#1]
# Introduction

This issue describes a proposal for how to launch a Livestream Viewer application showing livestreaming content from [NonCon 2020](https://www.parallele.at/not-a-conference-not-a-conjob/) from 3-6 April 2020.

NonCon 2020 is a replacement for EDCON 2020, which was cancelled citing concern for “the safety and health for the host city Vienna, the venue provider WU University, as well as all the speakers and attendees” in the wake of reports about Corona Virus.

This proposal can also be used for any other events which have been disrupted by Corona Virus, who wish to share live audio and video content with their audiences all over the world.

# Summary

In summary, launching `NonCon Live!` will require input from human(s) with the following skillsets:

- **Unix devOps** - highest priority skillset, without this, it can't happen
- **Kotlin developer** - also a high priority, without this, it will be hard
- **Graphic designer** - minimal input required, but it should look nice
- **Copywriter** - minimal input required, but it should scan well

Dependent on expertise, this human (these humans) ought to be able to do what is required to publish a smartphone / tablet application, with content served from a robust back-end livestreaming infrastructure, so that viewers of NonCon can watch live on their smartphone.

# Disclaimers

- the platform **will not record** the content - so remember to ensure that the on-site AV production team at your venue is capable of recording as well as streaming.
- The app only works on Android for now. [Apple support is on the roadmap](https://github.com/videoDAC/apple/issues/1).
- all software being used is experimental, and should be used at the human's own risk.

# Detailed Proposal

- Find a **Unix devOps human** to deploy and operate an instance of VideoDAC's [infinite-digital-stage](https://github.com/videoDAC/infinite-digital-stage) livestreaming platform
  - Infinite Digital Stage: is a full-stack of Livepeer's [`go-livepeer`](https://github.com/livepeer/go-livepeer/) software, running an `-offchain` "Broadcaster Orchestrator Transcoder" (BOT) Network per [bot-miner-setup](https://github.com/livepeer/bot-miner-setup).
  - Hardware Sizing: a Stage can run on 2GB RAM and 1 vCPU, maybe smaller. This can handle:
      - Receiving 1 source of livestream RTMP content, up to 1920x1080
         - Content likely to come from laptop + cameras / mics, using [`obs-studio`](https://github.com/obsproject/obs-studio), published to the Stage by on-site AV production team.
         - Can also receive a stream from [`FFmpeg`](https://github.com/FFmpeg/FFmpeg) e.g. for testing, or for streaming pre-recorded content from disk (e.g. `osaka-main-hall-day-4.mp4`)
      - Serving 4 encodings of the same content in different resolutions:
         - **256x144** - for viewers with _really slow_ internet e.g. `2G` mobile, `14.4k` modems
         - **426x240** - for viewers with _slow_ internet e.g. `3G` mobile, `56.6k` modems
         - **640x360** - for viewers with _ok_ internet e.g. 3.5G mobile, entry-level DSL
         - **Source (1920x1080)** - for viewers with _good_ internet, e.g. 4G mobile, strong DSL
         - To handle more sources and encodings, needs more CPU, or GPU, or buy Transcoding service from Livepeer, pay using Probabilistic Micropayments on Ethereum.
  - **Setup**: from clean install this will take <<10 minutes - here's [the short script](https://github.com/videoDAC/infinite-digital-stage/blob/master/BUIDL.md).
  - **Audit**: Livepeer's protocol and software have already been audited by Trail of Bits.
  - **Bandwidth**: stage's upstream bandwidth needs to be able to handle expected viewing volumes - someone needs to _do the math_.
  - **Content Distribution**: if expected viewing figures necessitate it, maybe build your own little CDN. Or try to talk to Swarm about it. 
  - **Recording**: _**LIVEPEER DOES NOT RECORD**_. Livepeer only streams. Livepeer is only streaming. No storing. So for storing recordings maybe also try to talk to Swarm.

- Find an **Kotlin dev human** to publish `Noncon Live!` viewer app:
  - She can use Video DAC's [Android Application Template](https://github.com/videoDAC/android/tree/master/android).
    - App can be configured however she wants (see [build instructions](https://github.com/videoDAC/android))
    - She can make this a 5 minute job, or a 4 hour job depending on how much she hates / loves the VideoDAC code.
    - Ask her to "comment out" the paywall / wallet stuff, then launch to Google Play.
  - Also, can build viewer app from scratch using [`exo-player`](https://medium.com/mindorks/implementing-exoplayer-for-beginners-in-kotlin-c534706bce4b) in Kotlin to play `hls` video.

- Find a **Graphic Design human** to do the artwork for submitting `NonCon Live!` to Google Play
  - Needs the following artwork:
    - 512x512 - Hi-res icon (for launcher) - 32-bit `PNG`
    - 1024x500 - Feature Graphic - `JPG` or 24-bit `PNG` (no alpha)
    - 180x120 - Promo Graphic - `JPG` or 24-bit `PNG` (no alpha)
    - 1280x720 - TV Banner - `JPG` or 24-bit `PNG` (no alpha)
  - Must have between 2 and 8 screenshots from app
    - Min length for any side: `320px`. Max length for any side: `3840px`.
    - `JPEG` or 24-bit `PNG` (no alpha)
  - [These are the assets used for Görli TV](https://github.com/videoDAC/community/files/4261448/Gorli.TV.Assets.-.Google.Play.Store.zip)

- Find **Copywriter human** to write the copy for submitting to Google Play
  - Needs the following copy:
    - Title (up to 50 characters), e.g. `Görli TV`
    - Short description (up to 80 characters), e.g. `Görli TV is a startup TV channel, where viewers pay in göETH to watch.`
    - Full description (up to 4000 characters), e.g. here is [the copy used for Görli TV](https://github.com/videoDAC/community/files/4261452/Gorli.TV.-.Full.description.txt)

Video DAC can only commit to the following at this time:
- be party to a groupchat containing at least the **Unix devOps human**, but also the **Kotlin dev human**, the **Graphic Design human** and the **Copywriter human**
  - This groupchat has the sole objective of launching the `NonCon Live!` viewer application.
- answer any direct questions made to VideoDAC in the chat.

In the meantime, Video DAC will continue to work on
- Writing recipes for how to use existing free and open-source software, for example, the [`infinite-digital-stage`](https://github.com/videoDAC/infinite-digital-stage);
- Raising [Github issues](github.com/videoDAC/android/issues) proposing new concepts using Livepeer and Ethereum;
- Adding Livepeer Token (LPT) bounties to these Github issues [using Gitcoin](https://gitcoin.co/criticaltv)
- Polishing the documentation (making it succinct but entertaining), to assist with onboarding new members of videoDAC.

# What is videoDAC?

videoDAC is a "decentralised autonomous community" (not an "organisation"), of humans working together to build video-enabled applications using Livepeer.

To find out more about videoDAC, check out [the community's Orchestrator campaign page on Livepeer protocol explorer](https://explorer.livepeer.org/accounts/0xdac817294c0c87ca4fa1895ef4b972eade99f2fd/campaign).

You can join the community, and support the project, by [staking your Livepeer Tokens (LPT) to the community's node](https://explorer.livepeer.org/accounts/0xdac817294c0c87ca4fa1895ef4b972eade99f2fd/staking).

**Comment by exiledsurfer** [comment]
Thx for this, CTV, tagging the noncon devops @geleeroyale in this, as well as @ligi kotlin dev par excelance.

**Comment by criticaltv** [comment]
Also @exiledsurfer, for clarity, there is also an untested iOS app at https://github.com/videoDAC/android/iOS which was specified to only be a video player app, and the paywall screen was never added.

But it has not been tested, only developed, and code released for testing. But the author predicts that it has a good chance of working.

**Comment by chrishobcroft** [comment]
Closing this issue, as NonCon have decided to stream using YouTube / Google.

CC @exiledsurfer
